### ISSUE TITLE
\right| should not be converted to∥

### ISSUE THREAD

**Issue by msmart** [osanshouo/latex2mathml#8]
Thanks for the library! I ran a few tests on the latest version (0.2.3) and noticed that: 

```
\left|12\cdot\left(3+54\right)^2-9\right\|
```
is converted to
```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mo stretchy="true" form="prefix">|</mo><mrow><mn>12</mn><mo>·</mo><msup><mrow><mo stretchy="true" form="prefix">(</mo><mrow><mn>3</mn><mo>+</mo><mn>54</mn></mrow><mo stretchy="true" form="postfix">)</mo></mrow><mn>2</mn></msup><mo>-</mo><mn>9</mn></mrow><mo stretchy="true" form="postfix">∥</mo></mrow></math>
```
Any ideas why the second absolute value bar is converted to the ∥?

**Comment by osanshouo** [comment]
@msmart Thank you for opening an issue! I'm glad you tried the crate.

In your LaTeX code `\left|12\cdot\left(3+54\right)^2-9\right\|`, you use `\|` instead of `|`. Because `\|` in LaTeX corresponds to a [double pipe](https://www.overleaf.com/learn/latex/Brackets_and_Parentheses), the crate seems to work correctly. Please try

```latex
\left|12\cdot\left(3+54\right)^2-9\right|
```

**Comment by msmart** [comment]
@osanshouo you are right. My mistake! Thanks a lot! Closing this issue!
